# Generated by Django 4.1.4 on 2022-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinglist',
            name='filter_operator_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textinglist',
            name='filter_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
